version: '3.6'

services:

  rabbitmq:
    image: rabbitmq:3.7-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379
    restart: always
